#!/usr/bin/env bash
# (c) Meta Platforms, Inc. and affiliates. Confidential and proprietary.

set -euo pipefail

if [[ "${SANDCASTLE:-}" == "1" ]]; then
    # If running in Sandcastle, we need to download fbpkg.
    echo "Running in Sandcastle, fetching supertd fbpkg" 1>&2
    FETCH_FBPKG="$(hg root)/fbcode/target_determinator/supertd/fetch_supertd_fbpkg"
    SUPERTD=$($FETCH_FBPKG)
    echo "Using supertd binary from $SUPERTD" 1>&2
else
    echo "Running locally, using supertd devfeature" 1>&2
    SUPERTD="supertd"
fi

exec "$SUPERTD" "$@"
